# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datahub.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..transaction import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdatahub.proto\x12\x07\x64\x61tahub\x1a\x11transaction.proto\"O\n\x0bRegisterReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x12\n\ncommitment\x18\x04 \x01(\t\"A\n\x11\x44\x61taCommitmentReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\"(\n\x12\x44\x61taCommitmentResp\x12\x12\n\ncommitment\x18\x01 \x01(\t2\x97\x01\n\x07\x44\x61taHub\x12<\n\x08Register\x12\x14.datahub.RegisterReq\x1a\x18.transaction.Transaction\"\x00\x12N\n\x11GetDataCommitment\x12\x1a.datahub.DataCommitmentReq\x1a\x1b.datahub.DataCommitmentResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datahub_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQ._serialized_start=45
  _REGISTERREQ._serialized_end=124
  _DATACOMMITMENTREQ._serialized_start=126
  _DATACOMMITMENTREQ._serialized_end=191
  _DATACOMMITMENTRESP._serialized_start=193
  _DATACOMMITMENTRESP._serialized_end=233
  _DATAHUB._serialized_start=236
  _DATAHUB._serialized_end=387
# @@protoc_insertion_point(module_scope)
