"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class RegisterReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDRESS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    COMMITMENT_FIELD_NUMBER: builtins.int
    address: typing.Text
    name: typing.Text
    index: builtins.int
    commitment: typing.Text
    def __init__(self,
        *,
        address: typing.Text = ...,
        name: typing.Text = ...,
        index: builtins.int = ...,
        commitment: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address",b"address","commitment",b"commitment","index",b"index","name",b"name"]) -> None: ...
global___RegisterReq = RegisterReq

class DataCommitmentReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDRESS_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    address: typing.Text
    name: typing.Text
    index: builtins.int
    def __init__(self,
        *,
        address: typing.Text = ...,
        name: typing.Text = ...,
        index: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address",b"address","index",b"index","name",b"name"]) -> None: ...
global___DataCommitmentReq = DataCommitmentReq

class DataCommitmentResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMITMENT_FIELD_NUMBER: builtins.int
    commitment: typing.Text
    def __init__(self,
        *,
        commitment: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["commitment",b"commitment"]) -> None: ...
global___DataCommitmentResp = DataCommitmentResp
