# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="mpc.proto",
    package="mpc",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tmpc.proto\x12\x03mpc""\n\x13RegisterNodeRequest\x12\x0b\n\x03url\x18\x01 \x01(\t"\x15\n\x13RegisterTaskRequest""\n\x0fJoinTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r"\x1f\n\x0cTrainRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r"9\n\nKeyRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\r\x12\r\n\x05\x65poch\x18\x02 \x01(\r\x12\x0b\n\x03key\x18\x03 \x01(\x0c"\x0e\n\x0c\x45ventRequest"g\n\rEventResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0e\n\x06taskId\x18\x04 \x01(\r\x12\r\n\x05\x65poch\x18\x05 \x01(\r\x12\x0b\n\x03key\x18\x06 \x01(\t2\xdb\x02\n\x03Mpc\x12@\n\x0cregisterNode\x12\x18.mpc.RegisterNodeRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x12@\n\x0cregisterTask\x12\x18.mpc.RegisterTaskRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x12\x38\n\x08joinTask\x12\x14.mpc.JoinTaskRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x12\x32\n\x05train\x12\x11.mpc.TrainRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x12.\n\x03key\x12\x0f.mpc.KeyRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x12\x32\n\x05\x65vent\x12\x11.mpc.EventRequest\x1a\x12.mpc.EventResponse"\x00\x30\x01\x62\x06proto3',
)


_REGISTERNODEREQUEST = _descriptor.Descriptor(
    name="RegisterNodeRequest",
    full_name="mpc.RegisterNodeRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="url",
            full_name="mpc.RegisterNodeRequest.url",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=18,
    serialized_end=52,
)


_REGISTERTASKREQUEST = _descriptor.Descriptor(
    name="RegisterTaskRequest",
    full_name="mpc.RegisterTaskRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=54,
    serialized_end=75,
)


_JOINTASKREQUEST = _descriptor.Descriptor(
    name="JoinTaskRequest",
    full_name="mpc.JoinTaskRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="task_id",
            full_name="mpc.JoinTaskRequest.task_id",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=77,
    serialized_end=111,
)


_TRAINREQUEST = _descriptor.Descriptor(
    name="TrainRequest",
    full_name="mpc.TrainRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="task_id",
            full_name="mpc.TrainRequest.task_id",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=113,
    serialized_end=144,
)


_KEYREQUEST = _descriptor.Descriptor(
    name="KeyRequest",
    full_name="mpc.KeyRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="task_id",
            full_name="mpc.KeyRequest.task_id",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="epoch",
            full_name="mpc.KeyRequest.epoch",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="key",
            full_name="mpc.KeyRequest.key",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=146,
    serialized_end=203,
)


_EVENTREQUEST = _descriptor.Descriptor(
    name="EventRequest",
    full_name="mpc.EventRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=205,
    serialized_end=219,
)


_EVENTRESPONSE = _descriptor.Descriptor(
    name="EventResponse",
    full_name="mpc.EventResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="mpc.EventResponse.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="address",
            full_name="mpc.EventResponse.address",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="url",
            full_name="mpc.EventResponse.url",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="taskId",
            full_name="mpc.EventResponse.taskId",
            index=3,
            number=4,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="epoch",
            full_name="mpc.EventResponse.epoch",
            index=4,
            number=5,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="key",
            full_name="mpc.EventResponse.key",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=221,
    serialized_end=324,
)

DESCRIPTOR.message_types_by_name["RegisterNodeRequest"] = _REGISTERNODEREQUEST
DESCRIPTOR.message_types_by_name["RegisterTaskRequest"] = _REGISTERTASKREQUEST
DESCRIPTOR.message_types_by_name["JoinTaskRequest"] = _JOINTASKREQUEST
DESCRIPTOR.message_types_by_name["TrainRequest"] = _TRAINREQUEST
DESCRIPTOR.message_types_by_name["KeyRequest"] = _KEYREQUEST
DESCRIPTOR.message_types_by_name["EventRequest"] = _EVENTREQUEST
DESCRIPTOR.message_types_by_name["EventResponse"] = _EVENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterNodeRequest = _reflection.GeneratedProtocolMessageType(
    "RegisterNodeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERNODEREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.RegisterNodeRequest)
    },
)
_sym_db.RegisterMessage(RegisterNodeRequest)

RegisterTaskRequest = _reflection.GeneratedProtocolMessageType(
    "RegisterTaskRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERTASKREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.RegisterTaskRequest)
    },
)
_sym_db.RegisterMessage(RegisterTaskRequest)

JoinTaskRequest = _reflection.GeneratedProtocolMessageType(
    "JoinTaskRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _JOINTASKREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.JoinTaskRequest)
    },
)
_sym_db.RegisterMessage(JoinTaskRequest)

TrainRequest = _reflection.GeneratedProtocolMessageType(
    "TrainRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRAINREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.TrainRequest)
    },
)
_sym_db.RegisterMessage(TrainRequest)

KeyRequest = _reflection.GeneratedProtocolMessageType(
    "KeyRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _KEYREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.KeyRequest)
    },
)
_sym_db.RegisterMessage(KeyRequest)

EventRequest = _reflection.GeneratedProtocolMessageType(
    "EventRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTREQUEST,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.EventRequest)
    },
)
_sym_db.RegisterMessage(EventRequest)

EventResponse = _reflection.GeneratedProtocolMessageType(
    "EventResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTRESPONSE,
        "__module__": "mpc_pb2"
        # @@protoc_insertion_point(class_scope:mpc.EventResponse)
    },
)
_sym_db.RegisterMessage(EventResponse)


_MPC = _descriptor.ServiceDescriptor(
    name="Mpc",
    full_name="mpc.Mpc",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=327,
    serialized_end=674,
    methods=[
        _descriptor.MethodDescriptor(
            name="registerNode",
            full_name="mpc.Mpc.registerNode",
            index=0,
            containing_service=None,
            input_type=_REGISTERNODEREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="registerTask",
            full_name="mpc.Mpc.registerTask",
            index=1,
            containing_service=None,
            input_type=_REGISTERTASKREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="joinTask",
            full_name="mpc.Mpc.joinTask",
            index=2,
            containing_service=None,
            input_type=_JOINTASKREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="train",
            full_name="mpc.Mpc.train",
            index=3,
            containing_service=None,
            input_type=_TRAINREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="key",
            full_name="mpc.Mpc.key",
            index=4,
            containing_service=None,
            input_type=_KEYREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="event",
            full_name="mpc.Mpc.event",
            index=5,
            containing_service=None,
            input_type=_EVENTREQUEST,
            output_type=_EVENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_MPC)

DESCRIPTOR.services_by_name["Mpc"] = _MPC

# @@protoc_insertion_point(module_scope)
