# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hlr.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from ..transaction import transaction_pb2
from . import hlr_pb2


class HLRBase(abc.ABC):

    @abc.abstractmethod
    async def CreateTask(self, stream: 'grpclib.server.Stream[hlr_pb2.CreateTaskReq, hlr_pb2.CreateTaskResp]') -> None:
        pass

    @abc.abstractmethod
    async def FinishTask(self, stream: 'grpclib.server.Stream[hlr_pb2.FinishTaskReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetTask(self, stream: 'grpclib.server.Stream[hlr_pb2.TaskReq, hlr_pb2.TaskResp]') -> None:
        pass

    @abc.abstractmethod
    async def StartRound(self, stream: 'grpclib.server.Stream[hlr_pb2.StartRoundReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetWeightCommitment(self, stream: 'grpclib.server.Stream[hlr_pb2.WeightCommitmentReq, hlr_pb2.WeightCommitmentResp]') -> None:
        pass

    @abc.abstractmethod
    async def JoinRound(self, stream: 'grpclib.server.Stream[hlr_pb2.JoinRoundReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetTaskRound(self, stream: 'grpclib.server.Stream[hlr_pb2.TaskRoundReq, hlr_pb2.TaskRoundResp]') -> None:
        pass

    @abc.abstractmethod
    async def SelectCandidates(self, stream: 'grpclib.server.Stream[hlr_pb2.CandidatesReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def UploadSeedCommitment(self, stream: 'grpclib.server.Stream[hlr_pb2.ShareCommitment, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def UploadSecretKeyCommitment(self, stream: 'grpclib.server.Stream[hlr_pb2.ShareCommitment, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetClientPublickKeys(self, stream: 'grpclib.server.Stream[hlr_pb2.PublicKeyReq, hlr_pb2.PublicKeyResp]') -> None:
        pass

    @abc.abstractmethod
    async def StartCalculation(self, stream: 'grpclib.server.Stream[hlr_pb2.CalculationReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def UploadResultCommitment(self, stream: 'grpclib.server.Stream[hlr_pb2.ResultCommitment, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetResultCommitment(self, stream: 'grpclib.server.Stream[hlr_pb2.ResultCommitmentReq, hlr_pb2.ResultCommitmentResp]') -> None:
        pass

    @abc.abstractmethod
    async def StartAggregation(self, stream: 'grpclib.server.Stream[hlr_pb2.AggregationReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def UploadSeed(self, stream: 'grpclib.server.Stream[hlr_pb2.Share, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def UploadSecretKey(self, stream: 'grpclib.server.Stream[hlr_pb2.Share, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def GetSecretShareDatas(self, stream: 'grpclib.server.Stream[hlr_pb2.SecretShareReq, hlr_pb2.SecretShareResp]') -> None:
        pass

    @abc.abstractmethod
    async def EndRound(self, stream: 'grpclib.server.Stream[hlr_pb2.EndRoundReq, transaction_pb2.Transaction]') -> None:
        pass

    @abc.abstractmethod
    async def Verify(self, stream: 'grpclib.server.Stream[hlr_pb2.VerifyReq, hlr_pb2.VerifyResp]') -> None:
        pass

    @abc.abstractmethod
    async def GetVerifierState(self, stream: 'grpclib.server.Stream[hlr_pb2.TaskReq, hlr_pb2.VerifyState]') -> None:
        pass

    @abc.abstractmethod
    async def ConfirmVerification(self, stream: 'grpclib.server.Stream[hlr_pb2.ConfirmReq, transaction_pb2.Transaction]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/hlr.HLR/CreateTask': grpclib.const.Handler(
                self.CreateTask,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.CreateTaskReq,
                hlr_pb2.CreateTaskResp,
            ),
            '/hlr.HLR/FinishTask': grpclib.const.Handler(
                self.FinishTask,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.FinishTaskReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetTask': grpclib.const.Handler(
                self.GetTask,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.TaskReq,
                hlr_pb2.TaskResp,
            ),
            '/hlr.HLR/StartRound': grpclib.const.Handler(
                self.StartRound,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.StartRoundReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetWeightCommitment': grpclib.const.Handler(
                self.GetWeightCommitment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.WeightCommitmentReq,
                hlr_pb2.WeightCommitmentResp,
            ),
            '/hlr.HLR/JoinRound': grpclib.const.Handler(
                self.JoinRound,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.JoinRoundReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetTaskRound': grpclib.const.Handler(
                self.GetTaskRound,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.TaskRoundReq,
                hlr_pb2.TaskRoundResp,
            ),
            '/hlr.HLR/SelectCandidates': grpclib.const.Handler(
                self.SelectCandidates,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.CandidatesReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/UploadSeedCommitment': grpclib.const.Handler(
                self.UploadSeedCommitment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.ShareCommitment,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/UploadSecretKeyCommitment': grpclib.const.Handler(
                self.UploadSecretKeyCommitment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.ShareCommitment,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetClientPublickKeys': grpclib.const.Handler(
                self.GetClientPublickKeys,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.PublicKeyReq,
                hlr_pb2.PublicKeyResp,
            ),
            '/hlr.HLR/StartCalculation': grpclib.const.Handler(
                self.StartCalculation,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.CalculationReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/UploadResultCommitment': grpclib.const.Handler(
                self.UploadResultCommitment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.ResultCommitment,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetResultCommitment': grpclib.const.Handler(
                self.GetResultCommitment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.ResultCommitmentReq,
                hlr_pb2.ResultCommitmentResp,
            ),
            '/hlr.HLR/StartAggregation': grpclib.const.Handler(
                self.StartAggregation,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.AggregationReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/UploadSeed': grpclib.const.Handler(
                self.UploadSeed,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.Share,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/UploadSecretKey': grpclib.const.Handler(
                self.UploadSecretKey,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.Share,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/GetSecretShareDatas': grpclib.const.Handler(
                self.GetSecretShareDatas,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.SecretShareReq,
                hlr_pb2.SecretShareResp,
            ),
            '/hlr.HLR/EndRound': grpclib.const.Handler(
                self.EndRound,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.EndRoundReq,
                transaction_pb2.Transaction,
            ),
            '/hlr.HLR/Verify': grpclib.const.Handler(
                self.Verify,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.VerifyReq,
                hlr_pb2.VerifyResp,
            ),
            '/hlr.HLR/GetVerifierState': grpclib.const.Handler(
                self.GetVerifierState,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.TaskReq,
                hlr_pb2.VerifyState,
            ),
            '/hlr.HLR/ConfirmVerification': grpclib.const.Handler(
                self.ConfirmVerification,
                grpclib.const.Cardinality.UNARY_UNARY,
                hlr_pb2.ConfirmReq,
                transaction_pb2.Transaction,
            ),
        }


class HLRStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateTask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/CreateTask',
            hlr_pb2.CreateTaskReq,
            hlr_pb2.CreateTaskResp,
        )
        self.FinishTask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/FinishTask',
            hlr_pb2.FinishTaskReq,
            transaction_pb2.Transaction,
        )
        self.GetTask = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetTask',
            hlr_pb2.TaskReq,
            hlr_pb2.TaskResp,
        )
        self.StartRound = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/StartRound',
            hlr_pb2.StartRoundReq,
            transaction_pb2.Transaction,
        )
        self.GetWeightCommitment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetWeightCommitment',
            hlr_pb2.WeightCommitmentReq,
            hlr_pb2.WeightCommitmentResp,
        )
        self.JoinRound = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/JoinRound',
            hlr_pb2.JoinRoundReq,
            transaction_pb2.Transaction,
        )
        self.GetTaskRound = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetTaskRound',
            hlr_pb2.TaskRoundReq,
            hlr_pb2.TaskRoundResp,
        )
        self.SelectCandidates = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/SelectCandidates',
            hlr_pb2.CandidatesReq,
            transaction_pb2.Transaction,
        )
        self.UploadSeedCommitment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/UploadSeedCommitment',
            hlr_pb2.ShareCommitment,
            transaction_pb2.Transaction,
        )
        self.UploadSecretKeyCommitment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/UploadSecretKeyCommitment',
            hlr_pb2.ShareCommitment,
            transaction_pb2.Transaction,
        )
        self.GetClientPublickKeys = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetClientPublickKeys',
            hlr_pb2.PublicKeyReq,
            hlr_pb2.PublicKeyResp,
        )
        self.StartCalculation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/StartCalculation',
            hlr_pb2.CalculationReq,
            transaction_pb2.Transaction,
        )
        self.UploadResultCommitment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/UploadResultCommitment',
            hlr_pb2.ResultCommitment,
            transaction_pb2.Transaction,
        )
        self.GetResultCommitment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetResultCommitment',
            hlr_pb2.ResultCommitmentReq,
            hlr_pb2.ResultCommitmentResp,
        )
        self.StartAggregation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/StartAggregation',
            hlr_pb2.AggregationReq,
            transaction_pb2.Transaction,
        )
        self.UploadSeed = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/UploadSeed',
            hlr_pb2.Share,
            transaction_pb2.Transaction,
        )
        self.UploadSecretKey = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/UploadSecretKey',
            hlr_pb2.Share,
            transaction_pb2.Transaction,
        )
        self.GetSecretShareDatas = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetSecretShareDatas',
            hlr_pb2.SecretShareReq,
            hlr_pb2.SecretShareResp,
        )
        self.EndRound = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/EndRound',
            hlr_pb2.EndRoundReq,
            transaction_pb2.Transaction,
        )
        self.Verify = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/Verify',
            hlr_pb2.VerifyReq,
            hlr_pb2.VerifyResp,
        )
        self.GetVerifierState = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/GetVerifierState',
            hlr_pb2.TaskReq,
            hlr_pb2.VerifyState,
        )
        self.ConfirmVerification = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hlr.HLR/ConfirmVerification',
            hlr_pb2.ConfirmReq,
            transaction_pb2.Transaction,
        )
