# type: ignore
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hlr_pb2 as hlr__pb2
from ..transaction import transaction_pb2 as transaction__pb2


class HLRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/hlr.HLR/CreateTask',
                request_serializer=hlr__pb2.CreateTaskReq.SerializeToString,
                response_deserializer=hlr__pb2.CreateTaskResp.FromString,
                )
        self.FinishTask = channel.unary_unary(
                '/hlr.HLR/FinishTask',
                request_serializer=hlr__pb2.FinishTaskReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/hlr.HLR/GetTask',
                request_serializer=hlr__pb2.TaskReq.SerializeToString,
                response_deserializer=hlr__pb2.TaskResp.FromString,
                )
        self.StartRound = channel.unary_unary(
                '/hlr.HLR/StartRound',
                request_serializer=hlr__pb2.StartRoundReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetWeightCommitment = channel.unary_unary(
                '/hlr.HLR/GetWeightCommitment',
                request_serializer=hlr__pb2.WeightCommitmentReq.SerializeToString,
                response_deserializer=hlr__pb2.WeightCommitmentResp.FromString,
                )
        self.JoinRound = channel.unary_unary(
                '/hlr.HLR/JoinRound',
                request_serializer=hlr__pb2.JoinRoundReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetTaskRound = channel.unary_unary(
                '/hlr.HLR/GetTaskRound',
                request_serializer=hlr__pb2.TaskRoundReq.SerializeToString,
                response_deserializer=hlr__pb2.TaskRoundResp.FromString,
                )
        self.SelectCandidates = channel.unary_unary(
                '/hlr.HLR/SelectCandidates',
                request_serializer=hlr__pb2.CandidatesReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.UploadSeedCommitment = channel.unary_unary(
                '/hlr.HLR/UploadSeedCommitment',
                request_serializer=hlr__pb2.ShareCommitment.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.UploadSecretKeyCommitment = channel.unary_unary(
                '/hlr.HLR/UploadSecretKeyCommitment',
                request_serializer=hlr__pb2.ShareCommitment.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetClientPublickKeys = channel.unary_unary(
                '/hlr.HLR/GetClientPublickKeys',
                request_serializer=hlr__pb2.PublicKeyReq.SerializeToString,
                response_deserializer=hlr__pb2.PublicKeyResp.FromString,
                )
        self.StartCalculation = channel.unary_unary(
                '/hlr.HLR/StartCalculation',
                request_serializer=hlr__pb2.CalculationReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.UploadResultCommitment = channel.unary_unary(
                '/hlr.HLR/UploadResultCommitment',
                request_serializer=hlr__pb2.ResultCommitment.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetResultCommitment = channel.unary_unary(
                '/hlr.HLR/GetResultCommitment',
                request_serializer=hlr__pb2.ResultCommitmentReq.SerializeToString,
                response_deserializer=hlr__pb2.ResultCommitmentResp.FromString,
                )
        self.StartAggregation = channel.unary_unary(
                '/hlr.HLR/StartAggregation',
                request_serializer=hlr__pb2.AggregationReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.UploadSeed = channel.unary_unary(
                '/hlr.HLR/UploadSeed',
                request_serializer=hlr__pb2.Share.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.UploadSecretKey = channel.unary_unary(
                '/hlr.HLR/UploadSecretKey',
                request_serializer=hlr__pb2.Share.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.GetSecretShareDatas = channel.unary_unary(
                '/hlr.HLR/GetSecretShareDatas',
                request_serializer=hlr__pb2.SecretShareReq.SerializeToString,
                response_deserializer=hlr__pb2.SecretShareResp.FromString,
                )
        self.EndRound = channel.unary_unary(
                '/hlr.HLR/EndRound',
                request_serializer=hlr__pb2.EndRoundReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )
        self.Verify = channel.unary_unary(
                '/hlr.HLR/Verify',
                request_serializer=hlr__pb2.VerifyReq.SerializeToString,
                response_deserializer=hlr__pb2.VerifyResp.FromString,
                )
        self.GetVerifierState = channel.unary_unary(
                '/hlr.HLR/GetVerifierState',
                request_serializer=hlr__pb2.TaskReq.SerializeToString,
                response_deserializer=hlr__pb2.VerifyState.FromString,
                )
        self.ConfirmVerification = channel.unary_unary(
                '/hlr.HLR/ConfirmVerification',
                request_serializer=hlr__pb2.ConfirmReq.SerializeToString,
                response_deserializer=transaction__pb2.Transaction.FromString,
                )


class HLRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeightCommitment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSeedCommitment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSecretKeyCommitment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientPublickKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCalculation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadResultCommitment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResultCommitment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAggregation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSecretKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecretShareDatas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerifierState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmVerification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HLRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=hlr__pb2.CreateTaskReq.FromString,
                    response_serializer=hlr__pb2.CreateTaskResp.SerializeToString,
            ),
            'FinishTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishTask,
                    request_deserializer=hlr__pb2.FinishTaskReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=hlr__pb2.TaskReq.FromString,
                    response_serializer=hlr__pb2.TaskResp.SerializeToString,
            ),
            'StartRound': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRound,
                    request_deserializer=hlr__pb2.StartRoundReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetWeightCommitment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeightCommitment,
                    request_deserializer=hlr__pb2.WeightCommitmentReq.FromString,
                    response_serializer=hlr__pb2.WeightCommitmentResp.SerializeToString,
            ),
            'JoinRound': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRound,
                    request_deserializer=hlr__pb2.JoinRoundReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetTaskRound': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskRound,
                    request_deserializer=hlr__pb2.TaskRoundReq.FromString,
                    response_serializer=hlr__pb2.TaskRoundResp.SerializeToString,
            ),
            'SelectCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectCandidates,
                    request_deserializer=hlr__pb2.CandidatesReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'UploadSeedCommitment': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadSeedCommitment,
                    request_deserializer=hlr__pb2.ShareCommitment.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'UploadSecretKeyCommitment': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadSecretKeyCommitment,
                    request_deserializer=hlr__pb2.ShareCommitment.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetClientPublickKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientPublickKeys,
                    request_deserializer=hlr__pb2.PublicKeyReq.FromString,
                    response_serializer=hlr__pb2.PublicKeyResp.SerializeToString,
            ),
            'StartCalculation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCalculation,
                    request_deserializer=hlr__pb2.CalculationReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'UploadResultCommitment': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadResultCommitment,
                    request_deserializer=hlr__pb2.ResultCommitment.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetResultCommitment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResultCommitment,
                    request_deserializer=hlr__pb2.ResultCommitmentReq.FromString,
                    response_serializer=hlr__pb2.ResultCommitmentResp.SerializeToString,
            ),
            'StartAggregation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAggregation,
                    request_deserializer=hlr__pb2.AggregationReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'UploadSeed': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadSeed,
                    request_deserializer=hlr__pb2.Share.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'UploadSecretKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadSecretKey,
                    request_deserializer=hlr__pb2.Share.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'GetSecretShareDatas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecretShareDatas,
                    request_deserializer=hlr__pb2.SecretShareReq.FromString,
                    response_serializer=hlr__pb2.SecretShareResp.SerializeToString,
            ),
            'EndRound': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRound,
                    request_deserializer=hlr__pb2.EndRoundReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=hlr__pb2.VerifyReq.FromString,
                    response_serializer=hlr__pb2.VerifyResp.SerializeToString,
            ),
            'GetVerifierState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerifierState,
                    request_deserializer=hlr__pb2.TaskReq.FromString,
                    response_serializer=hlr__pb2.VerifyState.SerializeToString,
            ),
            'ConfirmVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmVerification,
                    request_deserializer=hlr__pb2.ConfirmReq.FromString,
                    response_serializer=transaction__pb2.Transaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hlr.HLR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HLR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/CreateTask',
            hlr__pb2.CreateTaskReq.SerializeToString,
            hlr__pb2.CreateTaskResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/FinishTask',
            hlr__pb2.FinishTaskReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetTask',
            hlr__pb2.TaskReq.SerializeToString,
            hlr__pb2.TaskResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/StartRound',
            hlr__pb2.StartRoundReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWeightCommitment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetWeightCommitment',
            hlr__pb2.WeightCommitmentReq.SerializeToString,
            hlr__pb2.WeightCommitmentResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/JoinRound',
            hlr__pb2.JoinRoundReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetTaskRound',
            hlr__pb2.TaskRoundReq.SerializeToString,
            hlr__pb2.TaskRoundResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelectCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/SelectCandidates',
            hlr__pb2.CandidatesReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadSeedCommitment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/UploadSeedCommitment',
            hlr__pb2.ShareCommitment.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadSecretKeyCommitment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/UploadSecretKeyCommitment',
            hlr__pb2.ShareCommitment.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientPublickKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetClientPublickKeys',
            hlr__pb2.PublicKeyReq.SerializeToString,
            hlr__pb2.PublicKeyResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartCalculation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/StartCalculation',
            hlr__pb2.CalculationReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadResultCommitment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/UploadResultCommitment',
            hlr__pb2.ResultCommitment.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResultCommitment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetResultCommitment',
            hlr__pb2.ResultCommitmentReq.SerializeToString,
            hlr__pb2.ResultCommitmentResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartAggregation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/StartAggregation',
            hlr__pb2.AggregationReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadSeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/UploadSeed',
            hlr__pb2.Share.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadSecretKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/UploadSecretKey',
            hlr__pb2.Share.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSecretShareDatas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetSecretShareDatas',
            hlr__pb2.SecretShareReq.SerializeToString,
            hlr__pb2.SecretShareResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/EndRound',
            hlr__pb2.EndRoundReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/Verify',
            hlr__pb2.VerifyReq.SerializeToString,
            hlr__pb2.VerifyResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVerifierState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/GetVerifierState',
            hlr__pb2.TaskReq.SerializeToString,
            hlr__pb2.VerifyState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hlr.HLR/ConfirmVerification',
            hlr__pb2.ConfirmReq.SerializeToString,
            transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
