"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_CREATED_FIELD_NUMBER: builtins.int
    ROUND_STARTED_FIELD_NUMBER: builtins.int
    PARTNER_SELECTED_FIELD_NUMBER: builtins.int
    CALCULATION_STARTED_FIELD_NUMBER: builtins.int
    AGGREGATION_STARTED_FIELD_NUMBER: builtins.int
    ROUND_ENDED_FIELD_NUMBER: builtins.int
    TASK_FINISHED_FIELD_NUMBER: builtins.int
    HEARTBEAT_FIELD_NUMBER: builtins.int
    TASK_MEMBER_VERIFIED_FIELD_NUMBER: builtins.int
    TASK_VERIFICATION_CONFIRMED_FIELD_NUMBER: builtins.int
    DATA_REGISTERED_FIELD_NUMBER: builtins.int
    @property
    def task_created(self) -> global___TaskCreateEvent: ...
    @property
    def round_started(self) -> global___RoundStartedEvent: ...
    @property
    def partner_selected(self) -> global___PartnerSelectedEvent: ...
    @property
    def calculation_started(self) -> global___CalculationStartedEvent: ...
    @property
    def aggregation_started(self) -> global___AggregationStartedEvent: ...
    @property
    def round_ended(self) -> global___RoundEndedEvent: ...
    @property
    def task_finished(self) -> global___TaskFinishEvent: ...
    @property
    def heartbeat(self) -> global___HeartBeatEvent: ...
    @property
    def task_member_verified(self) -> global___TaskMemberVerifiedEvent: ...
    @property
    def task_verification_confirmed(self) -> global___TaskVerificationConfirmedEvent: ...
    @property
    def data_registered(self) -> global___DataRegisteredEvent: ...
    def __init__(self,
        *,
        task_created: typing.Optional[global___TaskCreateEvent] = ...,
        round_started: typing.Optional[global___RoundStartedEvent] = ...,
        partner_selected: typing.Optional[global___PartnerSelectedEvent] = ...,
        calculation_started: typing.Optional[global___CalculationStartedEvent] = ...,
        aggregation_started: typing.Optional[global___AggregationStartedEvent] = ...,
        round_ended: typing.Optional[global___RoundEndedEvent] = ...,
        task_finished: typing.Optional[global___TaskFinishEvent] = ...,
        heartbeat: typing.Optional[global___HeartBeatEvent] = ...,
        task_member_verified: typing.Optional[global___TaskMemberVerifiedEvent] = ...,
        task_verification_confirmed: typing.Optional[global___TaskVerificationConfirmedEvent] = ...,
        data_registered: typing.Optional[global___DataRegisteredEvent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["aggregation_started",b"aggregation_started","calculation_started",b"calculation_started","data_registered",b"data_registered","event",b"event","heartbeat",b"heartbeat","partner_selected",b"partner_selected","round_ended",b"round_ended","round_started",b"round_started","task_created",b"task_created","task_finished",b"task_finished","task_member_verified",b"task_member_verified","task_verification_confirmed",b"task_verification_confirmed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aggregation_started",b"aggregation_started","calculation_started",b"calculation_started","data_registered",b"data_registered","event",b"event","heartbeat",b"heartbeat","partner_selected",b"partner_selected","round_ended",b"round_ended","round_started",b"round_started","task_created",b"task_created","task_finished",b"task_finished","task_member_verified",b"task_member_verified","task_verification_confirmed",b"task_verification_confirmed"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["event",b"event"]) -> typing.Optional[typing_extensions.Literal["task_created","round_started","partner_selected","calculation_started","aggregation_started","round_ended","task_finished","heartbeat","task_member_verified","task_verification_confirmed","data_registered"]]: ...
global___Event = Event

class TaskCreateEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDRESS_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    DATASET_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    COMMITMENT_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    ENABLE_VERIFY_FIELD_NUMBER: builtins.int
    TOLERANCE_FIELD_NUMBER: builtins.int
    address: typing.Text
    task_id: typing.Text
    dataset: typing.Text
    url: typing.Text
    commitment: typing.Text
    task_type: typing.Text
    enable_verify: builtins.bool
    tolerance: builtins.int
    def __init__(self,
        *,
        address: typing.Text = ...,
        task_id: typing.Text = ...,
        dataset: typing.Text = ...,
        url: typing.Text = ...,
        commitment: typing.Text = ...,
        task_type: typing.Text = ...,
        enable_verify: builtins.bool = ...,
        tolerance: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address",b"address","commitment",b"commitment","dataset",b"dataset","enable_verify",b"enable_verify","task_id",b"task_id","task_type",b"task_type","tolerance",b"tolerance","url",b"url"]) -> None: ...
global___TaskCreateEvent = TaskCreateEvent

class RoundStartedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    round: builtins.int
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        round: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["round",b"round","task_id",b"task_id"]) -> None: ...
global___RoundStartedEvent = RoundStartedEvent

class PartnerSelectedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    round: builtins.int
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        round: builtins.int = ...,
        addrs: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","round",b"round","task_id",b"task_id"]) -> None: ...
global___PartnerSelectedEvent = PartnerSelectedEvent

class CalculationStartedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    round: builtins.int
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        round: builtins.int = ...,
        addrs: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","round",b"round","task_id",b"task_id"]) -> None: ...
global___CalculationStartedEvent = CalculationStartedEvent

class AggregationStartedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    round: builtins.int
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        round: builtins.int = ...,
        addrs: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","round",b"round","task_id",b"task_id"]) -> None: ...
global___AggregationStartedEvent = AggregationStartedEvent

class RoundEndedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    round: builtins.int
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        round: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["round",b"round","task_id",b"task_id"]) -> None: ...
global___RoundEndedEvent = RoundEndedEvent

class TaskFinishEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["task_id",b"task_id"]) -> None: ...
global___TaskFinishEvent = TaskFinishEvent

class HeartBeatEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___HeartBeatEvent = HeartBeatEvent

class TaskMemberVerifiedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    VERIFIED_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    address: typing.Text
    verified: builtins.bool
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        address: typing.Text = ...,
        verified: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address",b"address","task_id",b"task_id","verified",b"verified"]) -> None: ...
global___TaskMemberVerifiedEvent = TaskMemberVerifiedEvent

class TaskVerificationConfirmedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["task_id",b"task_id"]) -> None: ...
global___TaskVerificationConfirmedEvent = TaskVerificationConfirmedEvent

class DataRegisteredEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OWNER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    COMMITMENT_FIELD_NUMBER: builtins.int
    owner: typing.Text
    name: typing.Text
    index: builtins.int
    commitment: typing.Text
    def __init__(self,
        *,
        owner: typing.Text = ...,
        name: typing.Text = ...,
        index: builtins.int = ...,
        commitment: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["commitment",b"commitment","index",b"index","name",b"name","owner",b"owner"]) -> None: ...
global___DataRegisteredEvent = DataRegisteredEvent

class EventReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDRESS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    address: typing.Text
    timeout: builtins.int
    def __init__(self,
        *,
        address: typing.Text = ...,
        timeout: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address",b"address","timeout",b"timeout"]) -> None: ...
global___EventReq = EventReq
