# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..transaction import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\x12\x08identity\x1a\x11transaction.proto\"$\n\x07JoinReq\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\x08JoinResp\x12\x0f\n\x07tx_hash\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\",\n\x0cUpdateUrlReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\".\n\rUpdateNameReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1b\n\x08LeaveReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1e\n\x0bNodeInfoReq\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"6\n\x08NodeInfo\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"/\n\x0cNodeInfosReq\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"C\n\tNodeInfos\x12!\n\x05nodes\x18\x01 \x03(\x0b\x32\x12.identity.NodeInfo\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\xef\x02\n\x08Identity\x12/\n\x04Join\x12\x11.identity.JoinReq\x1a\x12.identity.JoinResp\"\x00\x12?\n\tUpdateUrl\x12\x16.identity.UpdateUrlReq\x1a\x18.transaction.Transaction\"\x00\x12\x41\n\nUpdateName\x12\x17.identity.UpdateNameReq\x1a\x18.transaction.Transaction\"\x00\x12\x37\n\x05Leave\x12\x12.identity.LeaveReq\x1a\x18.transaction.Transaction\"\x00\x12:\n\x0bGetNodeInfo\x12\x15.identity.NodeInfoReq\x1a\x12.identity.NodeInfo\"\x00\x12\x39\n\x08GetNodes\x12\x16.identity.NodeInfosReq\x1a\x13.identity.NodeInfos\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINREQ._serialized_start=47
  _JOINREQ._serialized_end=83
  _JOINRESP._serialized_start=85
  _JOINRESP._serialized_end=129
  _UPDATEURLREQ._serialized_start=131
  _UPDATEURLREQ._serialized_end=175
  _UPDATENAMEREQ._serialized_start=177
  _UPDATENAMEREQ._serialized_end=223
  _LEAVEREQ._serialized_start=225
  _LEAVEREQ._serialized_end=252
  _NODEINFOREQ._serialized_start=254
  _NODEINFOREQ._serialized_end=284
  _NODEINFO._serialized_start=286
  _NODEINFO._serialized_end=340
  _NODEINFOSREQ._serialized_start=342
  _NODEINFOSREQ._serialized_end=389
  _NODEINFOS._serialized_start=391
  _NODEINFOS._serialized_end=458
  _IDENTITY._serialized_start=461
  _IDENTITY._serialized_end=828
# @@protoc_insertion_point(module_scope)
