# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain.proto',
  package='chain',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63hain.proto\x12\x05\x63hain\"+\n\x08NodesReq\x12\x0c\n\x04page\x18\x01 \x01(\r\x12\x11\n\tpage_size\x18\x14 \x01(\r\"\x1f\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\'\n\tNodesResp\x12\x1a\n\x05nodes\x18\x01 \x03(\x0b\x32\x0b.chain.Node\"\x16\n\x07NodeReq\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1b\n\x08NodeResp\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"(\n\x07TaskReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1b\n\x08TaskResp\x12\x0f\n\x07task_id\x18\x01 \x01(\r\"+\n\x07JoinReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\r\"\x1b\n\x08JoinResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x08RoundReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\r\"\x1d\n\tRoundResp\x12\x10\n\x08round_id\x18\x03 \x01(\r\"I\n\x06KeyReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\r\x12\x10\n\x08round_id\x18\x03 \x01(\r\x12\x0b\n\x03key\x18\x04 \x01(\t\"\x1a\n\x07KeyResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1b\n\x08\x45ventReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"d\n\tEventResp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0f\n\x07task_id\x18\x04 \x01(\r\x12\r\n\x05\x65poch\x18\x05 \x01(\r\x12\x0b\n\x03key\x18\x06 \x01(\t2\xe1\x02\n\x05\x43hain\x12/\n\x08GetNodes\x12\x0f.chain.NodesReq\x1a\x10.chain.NodesResp\"\x00\x12\x31\n\x0cRegisterNode\x12\x0e.chain.NodeReq\x1a\x0f.chain.NodeResp\"\x00\x12/\n\nCreateTask\x12\x0e.chain.TaskReq\x1a\x0f.chain.TaskResp\"\x00\x12-\n\x08JoinTask\x12\x0e.chain.JoinReq\x1a\x0f.chain.JoinResp\"\x00\x12\x31\n\nStartRound\x12\x0f.chain.RoundReq\x1a\x10.chain.RoundResp\"\x00\x12\x30\n\rPublishPubKey\x12\r.chain.KeyReq\x1a\x0e.chain.KeyResp\"\x00\x12/\n\x06\x45vents\x12\x0f.chain.EventReq\x1a\x10.chain.EventResp\"\x00\x30\x01\x62\x06proto3'
)




_NODESREQ = _descriptor.Descriptor(
  name='NodesReq',
  full_name='chain.NodesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='chain.NodesReq.page', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='chain.NodesReq.page_size', index=1,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=65,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='chain.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chain.Node.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='chain.Node.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=98,
)


_NODESRESP = _descriptor.Descriptor(
  name='NodesResp',
  full_name='chain.NodesResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='chain.NodesResp.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=139,
)


_NODEREQ = _descriptor.Descriptor(
  name='NodeReq',
  full_name='chain.NodeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='chain.NodeReq.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=163,
)


_NODERESP = _descriptor.Descriptor(
  name='NodeResp',
  full_name='chain.NodeResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.NodeResp.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=192,
)


_TASKREQ = _descriptor.Descriptor(
  name='TaskReq',
  full_name='chain.TaskReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.TaskReq.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='chain.TaskReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=234,
)


_TASKRESP = _descriptor.Descriptor(
  name='TaskResp',
  full_name='chain.TaskResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='chain.TaskResp.task_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=263,
)


_JOINREQ = _descriptor.Descriptor(
  name='JoinReq',
  full_name='chain.JoinReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.JoinReq.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='chain.JoinReq.task_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=308,
)


_JOINRESP = _descriptor.Descriptor(
  name='JoinResp',
  full_name='chain.JoinResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chain.JoinResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=337,
)


_ROUNDREQ = _descriptor.Descriptor(
  name='RoundReq',
  full_name='chain.RoundReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.RoundReq.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='chain.RoundReq.task_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=383,
)


_ROUNDRESP = _descriptor.Descriptor(
  name='RoundResp',
  full_name='chain.RoundResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_id', full_name='chain.RoundResp.round_id', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=414,
)


_KEYREQ = _descriptor.Descriptor(
  name='KeyReq',
  full_name='chain.KeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.KeyReq.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='chain.KeyReq.task_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_id', full_name='chain.KeyReq.round_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.KeyReq.key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=489,
)


_KEYRESP = _descriptor.Descriptor(
  name='KeyResp',
  full_name='chain.KeyResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chain.KeyResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=517,
)


_EVENTREQ = _descriptor.Descriptor(
  name='EventReq',
  full_name='chain.EventReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='chain.EventReq.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=546,
)


_EVENTRESP = _descriptor.Descriptor(
  name='EventResp',
  full_name='chain.EventResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chain.EventResp.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='chain.EventResp.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='chain.EventResp.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='chain.EventResp.task_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='chain.EventResp.epoch', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.EventResp.key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=648,
)

_NODESRESP.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['NodesReq'] = _NODESREQ
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['NodesResp'] = _NODESRESP
DESCRIPTOR.message_types_by_name['NodeReq'] = _NODEREQ
DESCRIPTOR.message_types_by_name['NodeResp'] = _NODERESP
DESCRIPTOR.message_types_by_name['TaskReq'] = _TASKREQ
DESCRIPTOR.message_types_by_name['TaskResp'] = _TASKRESP
DESCRIPTOR.message_types_by_name['JoinReq'] = _JOINREQ
DESCRIPTOR.message_types_by_name['JoinResp'] = _JOINRESP
DESCRIPTOR.message_types_by_name['RoundReq'] = _ROUNDREQ
DESCRIPTOR.message_types_by_name['RoundResp'] = _ROUNDRESP
DESCRIPTOR.message_types_by_name['KeyReq'] = _KEYREQ
DESCRIPTOR.message_types_by_name['KeyResp'] = _KEYRESP
DESCRIPTOR.message_types_by_name['EventReq'] = _EVENTREQ
DESCRIPTOR.message_types_by_name['EventResp'] = _EVENTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodesReq = _reflection.GeneratedProtocolMessageType('NodesReq', (_message.Message,), {
  'DESCRIPTOR' : _NODESREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.NodesReq)
  })
_sym_db.RegisterMessage(NodesReq)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.Node)
  })
_sym_db.RegisterMessage(Node)

NodesResp = _reflection.GeneratedProtocolMessageType('NodesResp', (_message.Message,), {
  'DESCRIPTOR' : _NODESRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.NodesResp)
  })
_sym_db.RegisterMessage(NodesResp)

NodeReq = _reflection.GeneratedProtocolMessageType('NodeReq', (_message.Message,), {
  'DESCRIPTOR' : _NODEREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.NodeReq)
  })
_sym_db.RegisterMessage(NodeReq)

NodeResp = _reflection.GeneratedProtocolMessageType('NodeResp', (_message.Message,), {
  'DESCRIPTOR' : _NODERESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.NodeResp)
  })
_sym_db.RegisterMessage(NodeResp)

TaskReq = _reflection.GeneratedProtocolMessageType('TaskReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.TaskReq)
  })
_sym_db.RegisterMessage(TaskReq)

TaskResp = _reflection.GeneratedProtocolMessageType('TaskResp', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.TaskResp)
  })
_sym_db.RegisterMessage(TaskResp)

JoinReq = _reflection.GeneratedProtocolMessageType('JoinReq', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.JoinReq)
  })
_sym_db.RegisterMessage(JoinReq)

JoinResp = _reflection.GeneratedProtocolMessageType('JoinResp', (_message.Message,), {
  'DESCRIPTOR' : _JOINRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.JoinResp)
  })
_sym_db.RegisterMessage(JoinResp)

RoundReq = _reflection.GeneratedProtocolMessageType('RoundReq', (_message.Message,), {
  'DESCRIPTOR' : _ROUNDREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.RoundReq)
  })
_sym_db.RegisterMessage(RoundReq)

RoundResp = _reflection.GeneratedProtocolMessageType('RoundResp', (_message.Message,), {
  'DESCRIPTOR' : _ROUNDRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.RoundResp)
  })
_sym_db.RegisterMessage(RoundResp)

KeyReq = _reflection.GeneratedProtocolMessageType('KeyReq', (_message.Message,), {
  'DESCRIPTOR' : _KEYREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.KeyReq)
  })
_sym_db.RegisterMessage(KeyReq)

KeyResp = _reflection.GeneratedProtocolMessageType('KeyResp', (_message.Message,), {
  'DESCRIPTOR' : _KEYRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.KeyResp)
  })
_sym_db.RegisterMessage(KeyResp)

EventReq = _reflection.GeneratedProtocolMessageType('EventReq', (_message.Message,), {
  'DESCRIPTOR' : _EVENTREQ,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.EventReq)
  })
_sym_db.RegisterMessage(EventReq)

EventResp = _reflection.GeneratedProtocolMessageType('EventResp', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRESP,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.EventResp)
  })
_sym_db.RegisterMessage(EventResp)



_CHAIN = _descriptor.ServiceDescriptor(
  name='Chain',
  full_name='chain.Chain',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=651,
  serialized_end=1004,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNodes',
    full_name='chain.Chain.GetNodes',
    index=0,
    containing_service=None,
    input_type=_NODESREQ,
    output_type=_NODESRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterNode',
    full_name='chain.Chain.RegisterNode',
    index=1,
    containing_service=None,
    input_type=_NODEREQ,
    output_type=_NODERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTask',
    full_name='chain.Chain.CreateTask',
    index=2,
    containing_service=None,
    input_type=_TASKREQ,
    output_type=_TASKRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JoinTask',
    full_name='chain.Chain.JoinTask',
    index=3,
    containing_service=None,
    input_type=_JOINREQ,
    output_type=_JOINRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartRound',
    full_name='chain.Chain.StartRound',
    index=4,
    containing_service=None,
    input_type=_ROUNDREQ,
    output_type=_ROUNDRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PublishPubKey',
    full_name='chain.Chain.PublishPubKey',
    index=5,
    containing_service=None,
    input_type=_KEYREQ,
    output_type=_KEYRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Events',
    full_name='chain.Chain.Events',
    index=6,
    containing_service=None,
    input_type=_EVENTREQ,
    output_type=_EVENTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAIN)

DESCRIPTOR.services_by_name['Chain'] = _CHAIN

# @@protoc_insertion_point(module_scope)
