# type: ignore
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import delta_zk_pb2 as delta__zk__pb2


class ZKPStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.prove = channel.unary_stream(
                '/delta.ZKP/prove',
                request_serializer=delta__zk__pb2.Input.SerializeToString,
                response_deserializer=delta__zk__pb2.Proof.FromString,
                )


class ZKPServicer(object):
    """Missing associated documentation comment in .proto file."""

    def prove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZKPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'prove': grpc.unary_stream_rpc_method_handler(
                    servicer.prove,
                    request_deserializer=delta__zk__pb2.Input.FromString,
                    response_serializer=delta__zk__pb2.Proof.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'delta.ZKP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZKP(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def prove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/delta.ZKP/prove',
            delta__zk__pb2.Input.SerializeToString,
            delta__zk__pb2.Proof.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
